language: node_js
node_js:
  - "8.9.0"
install: ./scripts/local/setup.sh
script:
  - pushd src/server/ && ./node_modules/eslint/bin/eslint.js "src/**"
  - popd && ./scripts/local/build.sh
git:
  submodules: false
